services:
  web:
    build: .
    command: /code/docker-entrypoint.sh
    restart : always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5433:5432

volumes:
  postgres_data:
